### ISSUE TITLE
More details in error message

### ISSUE THREAD

**Issue by koriwi** [schnika/easybill#2]
is there no way to display the response of the api instead of only 

```
Easybill::Errors::BadRequestError - Bad Request:
```

**Comment by koriwi** [comment]
btw, love this gem

**Comment by koriwi** [comment]
you could just return the response.body parsed as json instead of response.message :)

**Comment by schnika** [comment]
Good point. Will do that

**Comment by schnika** [comment]
changed in c18ddd164290f1d67e8d58c3c3b0370c72707ced. however you need to parse the error message as json yourself. If I parse it as json before the error is getting raised, you get the string representation of the hash in the error message.

**Comment by koriwi** [comment]
nice !
